#!/bin/bash

echo "MYSQL_ROOT_PASSWORD = $MYSQL_ROOT_PASSWORD"
echo "MYSQL_USER          = $MYSQL_USER"
echo "MYSQL_PASSWORD      = $MYSQL_PASSWORD"
echo "MYSQL_DB_NAME       = $MYSQL_DB_NAME"

mysql -u root --password=$MYSQL_ROOT_PASSWORD <<EOF
CREATE DATABASE $MYSQL_DB_NAME DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON $MYSQL_DB_NAME.* TO '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
EOF

